"""Add stay_options to itineraries

Revision ID: e160e1a61c5a
Revises: 43e09a34f024
Create Date: 2026-09-24 18:23:27.392442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e160e1a61c5a'
down_revision: Union[str, Sequence[str], None] = '43e09a34f024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('stay_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itineraries', 'stay_options')
    # ### end Alembic commands ###
